#!/usr/bin/env bash
#===============================================================================
# init-swarm.sh - Initialize HSIS Project Structure
# Hierarchical Specialized Intelligence Swarm
#===============================================================================

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Default project name
PROJECT_NAME="${1:-hsis-project}"
PROJECT_DIR="${2:-.}"

#-------------------------------------------------------------------------------
# Logging functions
#-------------------------------------------------------------------------------
log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

#-------------------------------------------------------------------------------
# Create directory structure
#-------------------------------------------------------------------------------
create_directories() {
    log_info "Creating HSIS directory structure..."
    
    # Main directories
    mkdir -p "${PROJECT_DIR}/.swarm/intake"
    mkdir -p "${PROJECT_DIR}/.swarm/specs"
    mkdir -p "${PROJECT_DIR}/.swarm/artifacts"
    mkdir -p "${PROJECT_DIR}/.swarm/status"
    mkdir -p "${PROJECT_DIR}/.swarm/logs"
    mkdir -p "${PROJECT_DIR}/.swarm/escalations"
    
    # Documentation
    mkdir -p "${PROJECT_DIR}/docs/appendix"
    mkdir -p "${PROJECT_DIR}/docs/templates"
    
    # Architecture Decision Records
    mkdir -p "${PROJECT_DIR}/adrs"
    
    # Source and tests
    mkdir -p "${PROJECT_DIR}/src"
    mkdir -p "${PROJECT_DIR}/tests/unit"
    mkdir -p "${PROJECT_DIR}/tests/integration"
    mkdir -p "${PROJECT_DIR}/tests/e2e"
    
    # Scripts
    mkdir -p "${PROJECT_DIR}/scripts"
    
    log_success "Directory structure created"
}

#-------------------------------------------------------------------------------
# Create placeholder files
#-------------------------------------------------------------------------------
create_placeholders() {
    log_info "Creating placeholder files..."
    
    # .gitkeep files for empty directories
    touch "${PROJECT_DIR}/.swarm/intake/.gitkeep"
    touch "${PROJECT_DIR}/.swarm/specs/.gitkeep"
    touch "${PROJECT_DIR}/.swarm/artifacts/.gitkeep"
    touch "${PROJECT_DIR}/.swarm/status/.gitkeep"
    touch "${PROJECT_DIR}/.swarm/logs/.gitkeep"
    touch "${PROJECT_DIR}/.swarm/escalations/.gitkeep"
    touch "${PROJECT_DIR}/adrs/.gitkeep"
    touch "${PROJECT_DIR}/src/.gitkeep"
    touch "${PROJECT_DIR}/tests/unit/.gitkeep"
    touch "${PROJECT_DIR}/tests/integration/.gitkeep"
    touch "${PROJECT_DIR}/tests/e2e/.gitkeep"
    
    log_success "Placeholder files created"
}

#-------------------------------------------------------------------------------
# Create README
#-------------------------------------------------------------------------------
create_readme() {
    log_info "Creating README.md..."
    
    cat > "${PROJECT_DIR}/README.md" << 'EOF'
# Project Name

> Generated by Hierarchical Specialized Intelligence Swarm (HSIS)

## Overview

[Project description will be added after PM phase]

## Quick Start

```bash
# Install dependencies
make deps

# Run tests
make test

# Start application
make run
```

## Documentation

- [Product Requirements](docs/PRD.md)
- [Architecture Specification](docs/ARCHITECTURE.md)
- [Implementation Plan](docs/IMPLEMENTATION_PLAN.md)
- [Implementation Report](docs/IMPLEMENTATION_REPORT.md)

## Project Structure

```
├── .swarm/           # HSIS orchestration
│   ├── intake/       # Raw requirements
│   ├── specs/        # Generated specifications
│   ├── artifacts/    # Agent outputs
│   ├── status/       # Gate markers
│   ├── logs/         # Execution logs
│   └── escalations/  # Cross-role questions
├── docs/             # Documentation
├── adrs/             # Architecture Decision Records
├── src/              # Source code
├── tests/            # Test suites
└── scripts/          # Automation scripts
```

## HSIS Workflow Status

| Phase | Status | Gate |
|-------|--------|------|
| PM (Requirements) | ⏳ Pending | - |
| Architect (Design) | ⏳ Pending | - |
| Developer (Implementation) | ⏳ Pending | - |

## License

[License information]
EOF

    log_success "README.md created"
}

#-------------------------------------------------------------------------------
# Create CHANGELOG
#-------------------------------------------------------------------------------
create_changelog() {
    log_info "Creating CHANGELOG.md..."
    
    cat > "${PROJECT_DIR}/CHANGELOG.md" << EOF
# Changelog

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

## [Unreleased]

### Added
- Initial project structure created by HSIS init-swarm.sh
- Date: $(date +%Y-%m-%d)

### Changed

### Deprecated

### Removed

### Fixed

### Security
EOF

    log_success "CHANGELOG.md created"
}

#-------------------------------------------------------------------------------
# Create Makefile
#-------------------------------------------------------------------------------
create_makefile() {
    log_info "Creating Makefile..."
    
    cat > "${PROJECT_DIR}/Makefile" << 'EOF'
.PHONY: all deps lint test test-unit test-integration test-e2e coverage run clean help

# Default target
all: deps lint test

#-------------------------------------------------------------------------------
# Dependencies
#-------------------------------------------------------------------------------
deps:
	@echo "Installing dependencies..."
	# Add your dependency installation commands here
	# npm install
	# pip install -r requirements.txt
	# cargo build

#-------------------------------------------------------------------------------
# Quality Checks
#-------------------------------------------------------------------------------
lint:
	@echo "Running linter..."
	# Add your lint commands here
	# npm run lint
	# flake8 src/
	# cargo clippy

type-check:
	@echo "Running type checker..."
	# Add type check commands here
	# npm run type-check
	# mypy src/

fmt:
	@echo "Formatting code..."
	# Add format commands here
	# npm run format
	# black src/
	# cargo fmt

#-------------------------------------------------------------------------------
# Testing
#-------------------------------------------------------------------------------
test: test-unit test-integration

test-unit:
	@echo "Running unit tests..."
	# Add unit test commands here
	# npm run test:unit
	# pytest tests/unit/

test-integration:
	@echo "Running integration tests..."
	# Add integration test commands here
	# npm run test:integration
	# pytest tests/integration/

test-e2e:
	@echo "Running E2E tests..."
	# Add E2E test commands here
	# npm run test:e2e
	# pytest tests/e2e/

coverage:
	@echo "Running tests with coverage..."
	# Add coverage commands here
	# npm run test:coverage
	# pytest --cov=src tests/

#-------------------------------------------------------------------------------
# Application
#-------------------------------------------------------------------------------
run:
	@echo "Starting application..."
	# Add run commands here
	# npm start
	# python src/main.py

build:
	@echo "Building application..."
	# Add build commands here
	# npm run build
	# cargo build --release

#-------------------------------------------------------------------------------
# HSIS Workflow
#-------------------------------------------------------------------------------
swarm-init:
	@bash scripts/init-swarm.sh

swarm-pm:
	@bash scripts/run-pm.sh

swarm-architect:
	@bash scripts/run-architect.sh

swarm-developer:
	@bash scripts/run-developer.sh

swarm-full:
	@bash scripts/swarm-orchestrator.sh

verify-gates:
	@bash scripts/verify-gates.sh

#-------------------------------------------------------------------------------
# Utilities
#-------------------------------------------------------------------------------
clean:
	@echo "Cleaning build artifacts..."
	rm -rf dist/ build/ coverage/ .pytest_cache/ node_modules/
	find . -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null || true
	find . -type f -name "*.pyc" -delete 2>/dev/null || true

help:
	@echo "Available targets:"
	@echo "  deps              - Install dependencies"
	@echo "  lint              - Run linter"
	@echo "  type-check        - Run type checker"
	@echo "  fmt               - Format code"
	@echo "  test              - Run all tests (unit + integration)"
	@echo "  test-unit         - Run unit tests"
	@echo "  test-integration  - Run integration tests"
	@echo "  test-e2e          - Run E2E tests"
	@echo "  coverage          - Run tests with coverage"
	@echo "  run               - Start application"
	@echo "  build             - Build application"
	@echo "  swarm-init        - Initialize HSIS structure"
	@echo "  swarm-pm          - Run PM phase"
	@echo "  swarm-architect   - Run Architect phase"
	@echo "  swarm-developer   - Run Developer phase"
	@echo "  swarm-full        - Run full HSIS workflow"
	@echo "  verify-gates      - Verify all gate checklists"
	@echo "  clean             - Clean build artifacts"
	@echo "  help              - Show this help"
EOF

    log_success "Makefile created"
}

#-------------------------------------------------------------------------------
# Create .gitignore
#-------------------------------------------------------------------------------
create_gitignore() {
    log_info "Creating .gitignore..."
    
    cat > "${PROJECT_DIR}/.gitignore" << 'EOF'
# Dependencies
node_modules/
vendor/
.venv/
venv/
__pycache__/
*.pyc

# Build outputs
dist/
build/
target/
*.o
*.a

# IDE
.idea/
.vscode/
*.swp
*.swo
*~

# OS
.DS_Store
Thumbs.db

# Environment
.env
.env.local
.env.*.local
*.pem
*.key

# Logs
*.log
.swarm/logs/*.log

# Coverage
coverage/
.coverage
htmlcov/
.pytest_cache/

# Temporary
tmp/
temp/
*.tmp

# Secrets (never commit)
secrets/
credentials.json
service-account.json
EOF

    log_success ".gitignore created"
}

#-------------------------------------------------------------------------------
# Create swarm status file
#-------------------------------------------------------------------------------
create_status() {
    log_info "Creating swarm status file..."
    
    cat > "${PROJECT_DIR}/.swarm/status/workflow.json" << EOF
{
  "project": "${PROJECT_NAME}",
  "initialized": "$(date -Iseconds)",
  "phases": {
    "pm": {
      "status": "pending",
      "started": null,
      "completed": null,
      "gate_passed": false
    },
    "architect": {
      "status": "pending",
      "started": null,
      "completed": null,
      "gate_passed": false
    },
    "developer": {
      "status": "pending",
      "started": null,
      "completed": null,
      "gate_passed": false
    }
  },
  "current_phase": "pm",
  "blockers": [],
  "escalations": []
}
EOF

    log_success "Swarm status file created"
}

#-------------------------------------------------------------------------------
# Main
#-------------------------------------------------------------------------------
main() {
    echo ""
    echo "╔══════════════════════════════════════════════════════════════╗"
    echo "║     Hierarchical Specialized Intelligence Swarm (HSIS)       ║"
    echo "║                   Project Initialization                      ║"
    echo "╚══════════════════════════════════════════════════════════════╝"
    echo ""
    
    log_info "Initializing project: ${PROJECT_NAME}"
    log_info "Target directory: ${PROJECT_DIR}"
    echo ""
    
    create_directories
    create_placeholders
    create_readme
    create_changelog
    create_makefile
    create_gitignore
    create_status
    
    echo ""
    log_success "HSIS project initialized successfully!"
    echo ""
    echo "Next steps:"
    echo "  1. Add your intake requirements to .swarm/intake/"
    echo "  2. Run 'make swarm-pm' to start PM phase"
    echo "  3. Or run 'make swarm-full' for complete workflow"
    echo ""
}

main "$@"
